// <auto-generated />
namespace SethWebster.OpenLogging.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class addedpasswordtocllient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedpasswordtocllient));
        
        string IMigrationMetadata.Id
        {
            get { return "201311091635506_added-password-to-cllient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
