// <auto-generated />
namespace SethWebster.OpenLogging.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class addedapikeyataccountlevel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedapikeyataccountlevel));
        
        string IMigrationMetadata.Id
        {
            get { return "201311160002429_added-api-key-at-account-level"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
