// <auto-generated />
namespace SethWebster.OpenLogging.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class removepasswordfromclient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removepasswordfromclient));
        
        string IMigrationMetadata.Id
        {
            get { return "201311152355107_remove-password-from-client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
